[package]
name = "battleship"
version = "0.1.0"
edition = "2021"

[lib]
name = "battleship"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
clap = { version = "4.0", features = ["derive"] }
rayon = "1.8"
zstd = "0.13"
